# Simple example of CI to build a Docker container and push it to Amazon ECR
variables:
  DOCKER_REGISTRY: 157975149712.dkr.ecr.eu-north-1.amazonaws.com/techforlife  
  APP_NAME: producer-api
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - package

build:
  image: gradle:7.3.2-jdk17-alpine
  stage: build

  script:
    - cd producer && gradle build
    - pwd
  artifacts:
    paths:
      - producer/build/libs/*.jar

package:
  stage: package
  image: 
    name: docker:latest
  services:
    - docker:19-dind
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - aws --version
    - docker info
    - docker --version
  script:
    - pwd
    - cd producer && docker build -t $DOCKER_REGISTRY:$CI_PIPELINE_IID .
    - docker push $DOCKER_REGISTRY:$CI_PIPELINE_IID
