apiVersion: apps/v1
kind: Deployment
metadata:
  name: techforlife-producerapi-deployment
  namespace: development-ns
  labels:
    app: techforlife-producerapi-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: techforlife-producerapi-app
  template:
    metadata:
      labels:
        app: techforlife-producerapi-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: producer-api
        image: techforlife-producer-api-image
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux